services:
  - type: web
    name: dengidermo-1
    env: node
    plan: free
    buildCommand: npm install --no-audit --no-fund
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20.x
