services:
  - type: web
    name: dengidermo-1
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
